### PR TITLE
MDX Remote: Further Support For Github Integration

### PR DESCRIPTION
**Pull request by kijv**
Work in progress implementation of #479

- [X] Integration
- [ ] Docs
- [ ] Demo

### CODE REVIEW

**Comment by fuma-nama** [comment]
Btw since Next.js `fetch` also has its own cache, make sure to add `force-cache` to cache the request (on Next.js 15, this is required to enable fetch caching).

**Comment by fuma-nama** [comment]
Note that we only need to fetch the file content for a specific page when the user opens it. (In `[[...slugs]]/page.tsx`).
In my opinion, this part can be done by only `fetch` (with Next.js cache) and `fs.readFile` (on development mode).

To build page tree, we just need the frontmatter of MDX page and JSON files (`meta.json`), you might not need to cache the entire file.

**Comment by fuma-nama** [comment]
I came up with a diagram, it will be clear enought.

Fumadocs

**Comment by fuma-nama** [comment]
So I've made the GitHub API part for fetching Github file content, and maybe I can work on Hot reload later.
My idea is to run a Websocket on client and we notify the client to re-fetch page content (RSC payload) when a change is detected. I wrote a similar implementation for my `fuma-content` package so it's just copy-and-paste.

**Comment by fuma-nama** [comment]
Sure, also feel free to modify the MDX remote example app in the examples folder to test it out!

**Comment by fuma-nama** [comment]
Sounds good to me! Thanks for your help on this

**Comment by kijv** [comment]
@fuma-nama  No problem, its been fun to implement. When implementing the webook, use `cache.load({ lazy: true })` and `cache.fs().loadFile(getFileFromGithub(...))`. Also, will the Github cache API need to be documented?

**Comment by kijv** [comment]
For production I'm still unsure what exactly is the best course of action, I'll wait for the websocket to be implemented so I can have a better idea of how it will be expected to work during dev.

**Comment by kijv** [comment]
I just realized that this cache can be beyond just the Github integration, for example, the `localCache` instance is unrelated to the Github API (although it makes git trees from files, other than that everything is just about caching files). I'm not 100% confident if this cache functionality can be expanded to more things beyond this integration, just a possibility I thought of.

A strong example of its use is in `apps/docs`; you can see it takes a significant amount of time to load all the files at first, but with this cache it can just do that once (across multiple processes), then only make minor changes from there.

**Comment by fuma-nama** [comment]
I think Turbopack will fix this problem too

**Comment by fuma-nama** [comment]
> For production I'm still unsure what exactly is the best course of action for revalidation

GitHub WebHook will be a good choice, we only need to implement a route handler to receive notifications from GitHub. Or we can set the `revalidation` route segment config to an hour and let Next.js cache handles the rest

**Comment by kijv** [comment]
GitHub webhook + `unstable_cache` with `revalidateTag`?

**Comment by kijv** [comment]
@fuma-nama Most (if not all) functionality has been setup, except for the dev workflow. I will try to add more tests if possible.

**Comment by fuma-nama** [comment]
Thanks! I'm working on OpenAPI integration these days, will work on the websocket tonight (if possible)

**Comment by kijv** [comment]
Ok, no worries! Sorry if I feel like I'm rushing you!

**Comment by kijv** [comment]
Do you have any ideas for how to persist updates that are made to the cache during production. I'm trying to apply changes to cache then `revalidateTag`. But I think since the cache is loaded in the same file as `getPageTree` etc. it keeps using the cache file (doesn't update). I'll try researching some ways to fix this.

**Comment by kijv** [comment]
I don't know if `localCache` (and the base implementation) fits in the `mdx-remote` package, because one half actually relies on remote files `remoteCache` while the other half is just a cache for local files during development.

**Comment by kijv** [comment]
I will probably write a loader (turbopack compatible) which automatically switches between local and remote, probably at an empty file like `@fumadocs/mdx-remote/github/source`. This because in order for cache to work in prod you need `"use server"` directive and to re-export everything as an async function, which easily gets messy.

**Comment by fuma-nama** [comment]
Just write your cache to .next folder, and read it with fs

**Comment by fuma-nama** [comment]
I'm working on the watcher, might change some other code as well, don't change things right now to avoid merge conflicts

**Comment by fuma-nama** [comment]
dev environment: 
A compiler with watch mode support, most code copied from my `fuma-content` library. We might considering replacing it with `fuma-content` package later, but let's leave it first.

**Comment by kijv** [comment]
If you look at the example now, I think it removed most of the boilerplate and migrated to the similar `loader` API that is exported from `fumadocs-core/server`

**Comment by kijv** [comment]
Sorry, I just saw the "dont merge" message. I was experimenting a fix for prod workflow all day, my bad.

**Comment by kijv** [comment]
I can try to resolve the merge conflicts if there are any.

**Comment by kijv** [comment]
Once your add your commits I'll try to fit it in to what I have locally that I reverted

**Comment by fuma-nama** [comment]
Not a lot but added concurrently and WS server, now we can integrate WS server to Webpack/Turbopack

**Comment by fuma-nama** [comment]
Wait me for a day, coming up with some more changes

**Comment by kijv** [comment]
Ok sounds good

**Comment by kijv** [comment]
@fuma-nama 

I need `githubCacheStore` to be used when creating a new instance, because during during production it won't persist if its not saved, 

I also added a loader store locally because in order for the changes to actually *change* (in production) I found that within `getPageTree`, `getPages`, `getPage`, etc. (async functions from `loader`) you need to recall `loadFiles` (basically do the redo the work within each function) within the each function, so to avoid redoing the same work I just made a store to the git tree's hash.
**NOTE: I used a loader that changed `.../github/source` to export this function, wrapping the results in async functions with calls to `loader(...)` in each function, I found this easier because you just have to setup the wrapper with cache options around the nextConfig, then just import `loader`**  

I know that doing it this is kind of odd, but I tried other ways and this is the only way it worked in production (along with needing `"use server"`)

**Comment by kijv** [comment]
I have these changes locally, so need to add the yourself, I'm just waiting for you to finish up. Just wanted to make sure you knew the changes I would be making.

**Comment by fuma-nama** [comment]
This system may not be ideal fir implementing the dev server, I might do some breaking changes to current code. Will give you a short summary later

**Comment by kijv** [comment]
The system technically stays the same, because the loader can be production only, which means that abstraction not added in dev. I can easily make that change.

**Comment by kijv** [comment]
I also plan to use the loader as a way to abstract them having to invoke create cache themselves. I see the cache more as something that can be "hidden" because in reality they just pass repo and local options, but really that info is given to that cache.

**Comment by fuma-nama** [comment]
I noticed the problem of cache, Next.js apps hosted on serverless environments like Vercel are not able to persist the cache. After being inactive for a while, the cache will be cleared. To persist it, we can use vercel data cache. As mentioned in the docs, it must be used in conjunction with Next.js cache (unstable cache or fetch cache).

I am already working on a fix

**Comment by kijv** [comment]
I found GithubCacheStore or just a class with map to work. I already have a working production workflow, the only thing I was missing was a dev workflow

**Comment by kijv** [comment]
The code is in the latest "redo prod workflow..." commit

**Comment by kijv** [comment]
I tried using unstable_cache and I think it's less granular than revalidatePath combined with "use server"

**Comment by fuma-nama** [comment]
I'm trying to use `unstable_cache` or the fetch cache directly, and removed the custom in-memory cache implementation.
Also merged to the normal `loader` function of Source API, so that we can remove duplicated code

**Comment by fuma-nama** [comment]
The dev workflow now works, with a problem of cache persistence. We cannot persist the cache unless we host a websocket server that runs **outside** of Next.js runtime. Because all variables in the Next.js runtime cannot be persisted during fast refresh.

**Comment by fuma-nama** [comment]
I actually have an idea in mind tho, gonna implement that tomorrow

**Comment by fuma-nama** [comment]
Finished the GitHub integration.
The docs of MDX Remote and demo site are not finished

**Comment by fuma-nama** [comment]
And I want to deploy it to test our GitHub webhook integration, it would be pretty cool

**Comment by fuma-nama** [comment]
Since we have to merge this PR to continue deploying the demo site, I'm merging it now.

**Pull request merged**
