### PR TITLE
fix LaunchFast symbol

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by fuma-nama** [comment]
Hmm it isn't working, also make sure it's compatible with dark mode (the best if it uses `currentColor`)

**Comment by fuma-nama** [comment]
image

I fixed it for you ;)

**Comment by rishi-raj-jain** [comment]
> Hmm it isn't working, you need to apply `h-full` to the `svg` element, also make sure it's compatible with dark mode (the best if it uses `currentColor`)

Oh the latest commit would work, authorize that to deploy?

**Comment by rishi-raj-jain** [comment]
> image
> 
> I fixed it for you ;)

Wonderful! Can we have the outline around it of the circle (else it seems like a random icon)?

**Comment by fuma-nama** [comment]
image

Like this?

**Comment by rishi-raj-jain** [comment]
> image
> 
> Like this?

Exactly! Thank you!

**Pull request closed without merging**
