### PR TITLE
UI: Documentation and updates to API components

### PR DESCRIPTION
**Pull request by kyrylolvov**
Documentation:
- [x] Write documentation for `Root` component
- [x] Write documentation for `API` component
- [x] Write documentation for `APIInfo` component
- [x] Write documentation for `Property` component
- [x] Write documentation for `APIExample` component
- [x] Write documentation for `Requests`, `Request` components
- [x] Write documentation for `Responses`, `Response` components
- [x] Write documentation for `ResponseTypes`, `ExampleResponse`, `TypeScriptResponse` components

Components:
- [x] Modified APIExample component, so method type text looks vertically centered

### CODE REVIEW

**Comment by kyrylolvov** [comment]
@fuma-nama I have followed the 'style' of components docs that are already present for API. Should there be any changes made to already written pages in terms of content, language?

Also, I have added a little update for `APIInfo` component, as right now, the text inside the box doesn't look vertically centered. Please see the image below.
Screenshot 2024-06-22 at 5 36 52 PM

The update version looks like this.
Screenshot 2024-06-22 at 5 37 10 PM

**Comment by fuma-nama** [comment]
Sure

**Comment by fuma-nama** [comment]
I'd like to include it in the next release, you can notify me when you are ready :)

**Comment by kyrylolvov** [comment]
> I'd like to include it in the next release, you can notify me when you are ready :)

The updated APIInfo (vertically centered text) and docs for API components? I need to write a bit more for requests and responses components, and the PR will be ready. Will work on this today.

**Comment by fuma-nama** [comment]
Thanks! No rush at all, just do it as you wish

**Comment by kyrylolvov** [comment]
@fuma-nama I've just updated Requests page with link to `Tabs` for advanced usage, and links to `Tabs` and `Accordion` for Responses page, so there is no duplicate information. And added Reference section for new pages (Except Requests and Responses). Linted and wrote changeset.

Seems ready for review and merge.

**Comment by fuma-nama** [comment]
It works very well, thanks for your contribution!

**Pull request merged**
