### PR TITLE
Added UI component СontributorsСounter with and without useSwr support

### PR DESCRIPTION
**Pull request by changeelog**
[Contributors Counter Component Thingy #515](https://github.com/fuma-nama/fumadocs/discussions/515)

Implement two versions of the ContributorCounter component:

**1. ContributorCounter:** Uses standard React hooks for data fetching and state management.
**2. ContributorCounterSWR:** Utilizes the SWR library for data fetching and caching.

Both components display the total number of contributors and a subset of randomly selected contributors for a given GitHub repository.

TODO: 

1) Evaluate the necessity of SWR for this use case. If SWR's benefits are limited to this component specifically, we may want to stick with the standard React implementation either way it would be an overkill. SWR is used in other places of the project (with the Searches), yet it is never used in docs.
2) Add avatar placeholders - ✔️
3) Handle pagination to retrieve all commits, because GitHub's REST API paginates it's responses

## ContributorCounter Props

| Prop. | Type | Default | Description |
|-|-|-|-|
| repoOwner | string | - | The owner of the GitHub repo |
| repoName | string | - | The name of the GitHub repo |
| displayCount | number | 4 | The number of random contributors to display |
| intersectionThreshold | number | 0.1 | The threshold for the Intersection Observer. See [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) |

## Usage

```
<ContributorCounter
  repoOwner="fuma-nama"
  repoName="fumadocs"
  displayCount={4}
  intersectionThreshold={0.1}
/>
```

### CODE REVIEW

**Comment by fuma-nama** [comment]
I’m thinking about ISR, perhaps we can use RSC to show the top contributors, keeping our landing page as light as possible

**Comment by fuma-nama** [comment]
Also you can use GET /repos/:owner/:repo/contributors

**Comment by changeelog** [comment]
> I’m thinking about ISR,

Does it work in APP directory tho? I thought ISR was pages directory specific

**Comment by changeelog** [comment]
> Also you can use GET /repos/:owner/:repo/contributors

Maybe I'm doing something wrong but this code

image

Will only return contributors from insights -> contributors (top ones from top to bottom). The thing is GitHub API set's the max `per_page` to 100.

image

I was thinking we can implement pagination best do it recursively or iteratively

**Comment by fuma-nama** [comment]
I don't think we won't have more than 100 contributors and we are only going to display the top contributors (maybe the top 20 contributors)

**Comment by changeelog** [comment]
I'm not deadge! It seems the issue I've had might be related to API rate limits or authentication. Using Octokit (client for GitHub API) seems not appealing to me as well. You either deal with tokens using JWT (https://github.com/octokit/auth-app.js/[https://github.com/octokit/auth-app.js/]), or, if using PAT (Personal Access Tokens) implement some kind of token rotation thingy maybe.

Soo, maybe the current solution is enough for now and, if needed, could be scaled and improved later. I'm polishing the code now for the final version of it.

**Comment by changeelog** [comment]
Hey, pre-commit update, now the thing looks like this:

**Comment by fuma-nama** [comment]
Looks good to me, merging it now :)

**Pull request merged**
